controller_manager:
  ros__parameters:
    update_rate: 500 # Hz

    neural_controller:
      type: neural_controller/NeuralController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

imu_sensor_broadcaster:
  ros__parameters:
    update_rate: 100
    frame_id: base_link
    sensor_name: imu_sensor

neural_controller:
  ros__parameters:
    repeat_action: 10

    gain_multiplier: 1.0
    estop_kd: 0.1

    joint_names:
      [
        "leg_front_r_1",
        "leg_front_r_2",
        "leg_front_r_3",
        "leg_front_l_1",
        "leg_front_l_2",
        "leg_front_l_3",
        "leg_back_r_1",
        "leg_back_r_2",
        "leg_back_r_3",
        "leg_back_l_1",
        "leg_back_l_2",
        "leg_back_l_3",
      ]

    default_joint_pos:
      [0.26, 0.0, -0.52, -0.26, 0.0, 0.52, 0.26, 0.0, -0.52, -0.26, 0.0, 0.52]

    init_kps: [7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5]
    init_kds:
      [0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25]

    init_duration: 2.0
    fade_in_duration: 2.0

    action_types:
      [
        "position",
        "position",
        "position",
        "position",
        "position",
        "position",
        "position",
        "position",
        "position",
        "position",
        "position",
        "position",
      ]

    max_body_angle: 1.5

    model_path: "$(find-pkg-share neural_controller)/launch/policy_latest.json"

teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 0.75
      y: 0.5

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 2.0

    require_enable_button: false

joy_node:
  ros__parameters:
    dev: "/dev/input/js0"
    autorepeat_rate: 50.0
    coalesce_interval: 0.02

joint_state_broadcaster:
  ros__parameters:
    update_rate: 250
    use_local_topics: false
